.read dataEmployees.sql
.read dataAccount.sql
.read dataClient.sql
.read dataManifest.sql
.read dataPurchaseOrder.sql
.read dataVehicle.sql
.read dataShipmentOut.sql
.read dataShipmentIn.sql
.read dataPart.sql
.read dataPartsList.sql
.read dataMaintenance.sql
.read dataProduct.sql
.read dataManifestID.sql
