# Generated by Django 4.1.7 on 2023-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseOrderID', models.IntegerField()),
                ('productID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='purchaseOrder',
            fields=[
                ('purchaseOrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('costShippingHandling', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
