# Generated by Django 4.1.7 on 2023-03-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0003_orderitem_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipmentIn',
            fields=[
                ('shipID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('clientID', models.IntegerField()),
                ('vehID', models.IntegerField()),
                ('departure', models.DateTimeField()),
                ('estArrival', models.DateTimeField()),
                ('arrived', models.BooleanField()),
                ('payment', models.BooleanField()),
                ('driver', models.IntegerField()),
                ('purchaseOrder', models.IntegerField()),
            ],
        ),
    ]
