# Generated by Django 4.1.7 on 2023-04-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0004_shipmentin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentin',
            name='clientID',
        ),
        migrations.AddField(
            model_name='shipmentin',
            name='city',
            field=models.CharField(default='city', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentin',
            name='clientName',
            field=models.CharField(default='client', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentin',
            name='state',
            field=models.CharField(default='al', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentin',
            name='street',
            field=models.CharField(default='111 fart drive', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentin',
            name='zipcode',
            field=models.CharField(default='666666', max_length=6),
            preserve_default=False,
        ),
    ]
