# Generated by Django 4.1.7 on 2023-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0007_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(max_length=5)),
                ('text', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=40)),
            ],
        ),
    ]
