# Generated by Django 4.1.7 on 2023-04-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0008_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='manifest',
            fields=[
                ('manifestID', models.IntegerField(primary_key=True, serialize=False)),
                ('costShippingHandling', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='manifestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestID', models.IntegerField()),
                ('productID', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
