# Generated by Django 4.1.7 on 2023-04-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0009_manifest_manifestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('partID', models.IntegerField(primary_key=True, serialize=False)),
                ('onHand', models.IntegerField()),
                ('partName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehID', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('vehType', models.CharField(max_length=20)),
                ('loadCapacity', models.IntegerField()),
                ('height', models.IntegerField()),
                ('partsList', models.IntegerField()),
            ],
        ),
    ]
