# Generated by Django 4.1.7 on 2023-04-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0010_part_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='partsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.IntegerField()),
                ('partID', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
