# Generated by Django 4.1.7 on 2023-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0012_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cellPhone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='homePhone',
            field=models.CharField(max_length=10),
        ),
    ]
