# Generated by Django 4.1.7 on 2023-04-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckr', '0013_alter_employee_cellphone_alter_employee_homephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='yearmonth',
            fields=[
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('period', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
    ]
